export default {
  id: "tokenrouter",
  priority: 117,
  alias: "tokenrouter",
  uiAlias: "tokenrouter",
  display: {
    name: "TokenRouter",
    icon: "route",
    color: "#8B5CF6",
    textIcon: "TR",
    website: "https://www.tokenrouter.com",
    notice: {
      apiKeyUrl: "https://www.tokenrouter.com",
    },
  },
  category: "apikey",
  transport: {
    baseUrl: "https://api.tokenrouter.com/v1/chat/completions",
    validateUrl: "https://api.tokenrouter.com/v1/models",
  },
  serviceKinds: ["llm", "embedding", "image"],
  embeddingConfig: {
    baseUrl: "https://api.tokenrouter.com/v1/embeddings",
    authType: "apikey",
    authHeader: "bearer",
  },
  imageConfig: {
    baseUrl: "https://api.tokenrouter.com/v1/images/generations",
  },
  models: [
    { id: "minimax-m3", name: "MiniMax M3" },
    { id: "gemini-3.5-flash", name: "Gemini 3.5 Flash" },
    { id: "glm-5.2", name: "GLM 5.2" },
    { id: "glm-5.2-free", name: "GLM 5.2 Free" },
    { id: "gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "gpt-5.5", name: "GPT-5.5" },
    { id: "gpt-5.6-sol", name: "GPT-5.6 Sol" },
    { id: "gpt-5.6-terra", name: "GPT-5.6 Terra" },
    { id: "gpt-5.4", name: "GPT-5.4" },
    { id: "gemini-3-flash-preview", name: "Gemini 3 Flash Preview" },
    { id: "claude-opus-4.6", name: "Claude Opus 4.6" },
    { id: "claude-opus-4.7", name: "Claude Opus 4.7" },
    { id: "claude-opus-4.8", name: "Claude Opus 4.8" },
    { id: "claude-sonnet-4.6", name: "Claude Sonnet 4.6" },
    { id: "claude-haiku-4.5", name: "Claude Haiku 4.5" },
    { id: "kimi-k3", name: "Kimi K3" },
    { id: "kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "qwen3.7-max", name: "Qwen 3.7 Max" },
    { id: "qwen3.6-plus", name: "Qwen 3.6 Plus" },
    { id: "mimo-v2.5-pro", name: "Mimo V2.5 Pro" },
    { id: "anthropic/claude-haiku-4.5", name: "Claude Haiku 4.5" },
    { id: "anthropic/claude-sonnet-4.6", name: "Claude Sonnet 4.6" },
    { id: "anthropic/claude-opus-4.8", name: "Claude Opus 4.8" },
    { id: "anthropic/claude-opus-4.8-fast", name: "Claude Opus 4.8 Fast" },
    { id: "openai/gpt-5.4", name: "Gpt 5.4" },
    { id: "openai/gpt-5.4-mini", name: "Gpt 5.4 Mini" },
    { id: "openai/gpt-5.4-pro", name: "Gpt 5.4 Pro" },
    { id: "openai/gpt-5.5", name: "Gpt 5.5" },
    { id: "openai/gpt-5.6-sol", name: "Gpt 5.6 Sol" },
    { id: "google/gemini-3.5-flash", name: "Gemini 3.5 Flash" },
    { id: "google/gemini-3.6-flash", name: "Gemini 3.6 Flash" },
    { id: "deepseek/deepseek-v4-flash", name: "Deepseek V4 Flash" },
    { id: "deepseek/deepseek-v4-pro", name: "Deepseek V4 Pro" },
    { id: "qwen/qwen3-coder-next", name: "Qwen3 Coder Next" },
    { id: "qwen/qwen3.7-max", name: "Qwen3.7 Max" },
    { id: "qwen/qwen3.8-max", name: "Qwen3.8 Max" },
    { id: "moonshotai/kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "moonshotai/kimi-k3-free", name: "Kimi K3 Free" },
    { id: "z-ai/glm-5.3-free", name: "Glm 5.3 Free" },
    { id: "z-ai/glm-5.2", name: "Glm 5.2" },
    { id: "z-ai/glm-5-turbo", name: "Glm 5 Turbo" },
    { id: "x-ai/grok-4.5", name: "Grok 4.5" },
  ],
  modelsFetcher: { url: "https://api.tokenrouter.com/v1/models", type: "openai" },
  passthroughModels: true,
};
